import img1album1 from '../views/Client/Album/AlbumDtail/images/img1album1.png';
import img2album1 from '../views/Client/Album/AlbumDtail/images/img2album1.png';
import img3album1 from '../views/Client/Album/AlbumDtail/images/img3album1.png';
import img4album1 from '../views/Client/Album/AlbumDtail/images/img4album1.png';

import img1album2 from '../views/Client/Album/AlbumDtail/images/img1album2.png';
import img2album2 from '../views/Client/Album/AlbumDtail/images/img2album2.png';
import img3album2 from '../views/Client/Album/AlbumDtail/images/img3album2.png';
import img4album2 from '../views/Client/Album/AlbumDtail/images/img4album2.png';

import img1album3 from '../views/Client/Album/AlbumDtail/images/img1album3.png';
import img2album3 from '../views/Client/Album/AlbumDtail/images/img2album3.png';
import img3album3 from '../views/Client/Album/AlbumDtail/images/img3album3.png';
import img4album3 from '../views/Client/Album/AlbumDtail/images/img2album3.png';

import img1album4 from '../views/Client/Album/AlbumDtail/images/img1album4.png';
import img2album4 from '../views/Client/Album/AlbumDtail/images/img2album4.png';
import img3album4 from '../views/Client/Album/AlbumDtail/images/img3album4.png';
import img4album4 from '../views/Client/Album/AlbumDtail/images/img2album4.png';

import img1album5 from '../views/Client/Album/AlbumDtail/images/img1album5.png';
import img2album5 from '../views/Client/Album/AlbumDtail/images/img2album5.png';
import img3album5 from '../views/Client/Album/AlbumDtail/images/img3album5.png';
import img4album5 from '../views/Client/Album/AlbumDtail/images/img2album5.png';

export const Concepts = [
  {
    DamCuoi: [
      {
        id: 1,
        imgbg: img1album1,
        imgbg2: img2album1,
        imgbg3: img3album1,
        imgbg4: img4album1,
        name: 'album1',
      },
      {
        id: 2,
        imgbg: img1album2,
        imgbg2: img2album2,
        imgbg3: img3album2,
        imgbg4: img4album2,
        name: 'album2',
      },
      {
        id: 3,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
      {
        id: 4,
        imgbg: img1album4,
        imgbg2: img2album4,
        imgbg3: img3album4,
        imgbg4: img4album4,
        name: 'album4',
      },
      {
        id: 5,
        imgbg: img1album5,
        imgbg2: img2album5,
        imgbg3: img3album5,
        imgbg4: img4album5,
        name: 'album5',
      },
      {
        id: 6,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
    ],
    EmBe: [
      {
        id: 1,
        imgbg: img1album1,
        imgbg2: img2album1,
        imgbg3: img3album1,
        imgbg4: img4album1,
        name: 'album1',
      },
      {
        id: 2,
        imgbg: img1album2,
        imgbg2: img2album2,
        imgbg3: img3album2,
        imgbg4: img4album2,
        name: 'album2',
      },
      {
        id: 3,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
      {
        id: 4,
        imgbg: img1album4,
        imgbg2: img2album4,
        imgbg3: img3album4,
        imgbg4: img4album4,
        name: 'album4',
      },
      {
        id: 5,
        imgbg: img1album5,
        imgbg2: img2album5,
        imgbg3: img3album5,
        imgbg4: img4album5,
        name: 'album5',
      },
      {
        id: 6,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
    ],
    Prewedding: [
      {
        id: 1,
        imgbg: img1album1,
        imgbg2: img2album1,
        imgbg3: img3album1,
        imgbg4: img4album1,
        name: 'album1',
      },
      {
        id: 2,
        imgbg: img1album2,
        imgbg2: img2album2,
        imgbg3: img3album2,
        imgbg4: img4album2,
        name: 'album2',
      },
      {
        id: 3,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
      {
        id: 4,
        imgbg: img1album4,
        imgbg2: img2album4,
        imgbg3: img3album4,
        imgbg4: img4album4,
        name: 'album4',
      },
      {
        id: 5,
        imgbg: img1album5,
        imgbg2: img2album5,
        imgbg3: img3album5,
        imgbg4: img4album5,
        name: 'album5',
      },
      {
        id: 6,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
    ],
    NgoaiCanh: [
      {
        id: 1,
        imgbg: img1album1,
        imgbg2: img2album1,
        imgbg3: img3album1,
        imgbg4: img4album1,
        name: 'album1',
      },
      {
        id: 2,
        imgbg: img1album2,
        imgbg2: img2album2,
        imgbg3: img3album2,
        imgbg4: img4album2,
        name: 'album2',
      },
      {
        id: 3,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
      {
        id: 4,
        imgbg: img1album4,
        imgbg2: img2album4,
        imgbg3: img3album4,
        imgbg4: img4album4,
        name: 'album4',
      },
      {
        id: 5,
        imgbg: img1album5,
        imgbg2: img2album5,
        imgbg3: img3album5,
        imgbg4: img4album5,
        name: 'album5',
      },
      {
        id: 6,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
    ],
    CapDoi: [
      {
        id: 1,
        imgbg: img1album1,
        imgbg2: img2album1,
        imgbg3: img3album1,
        imgbg4: img4album1,
        name: 'album1',
      },
      {
        id: 2,
        imgbg: img1album2,
        imgbg2: img2album2,
        imgbg3: img3album2,
        imgbg4: img4album2,
        name: 'album2',
      },
      {
        id: 3,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
      {
        id: 4,
        imgbg: img1album4,
        imgbg2: img2album4,
        imgbg3: img3album4,
        imgbg4: img4album4,
        name: 'album4',
      },
      {
        id: 5,
        imgbg: img1album5,
        imgbg2: img2album5,
        imgbg3: img3album5,
        imgbg4: img4album5,
        name: 'album5',
      },
      {
        id: 6,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
    ],
    GiaDinh: [
      {
        id: 1,
        imgbg: img1album1,
        imgbg2: img2album1,
        imgbg3: img3album1,
        imgbg4: img4album1,
        name: 'album1',
      },
      {
        id: 2,
        imgbg: img1album2,
        imgbg2: img2album2,
        imgbg3: img3album2,
        imgbg4: img4album2,
        name: 'album2',
      },
      {
        id: 3,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
      {
        id: 4,
        imgbg: img1album4,
        imgbg2: img2album4,
        imgbg3: img3album4,
        imgbg4: img4album4,
        name: 'album4',
      },
      {
        id: 5,
        imgbg: img1album5,
        imgbg2: img2album5,
        imgbg3: img3album5,
        imgbg4: img4album5,
        name: 'album5',
      },
      {
        id: 6,
        imgbg: img1album3,
        imgbg2: img2album3,
        imgbg3: img3album3,
        imgbg4: img4album3,
        name: 'album3',
      },
    ],
  },
];

export const AlbumAll = [
  {
    id: 1,
    imgbg: img1album1,
    imgbg2: img2album1,
    imgbg3: img3album1,
    imgbg4: img4album1,
    name: 'album1',
  },
  {
    id: 2,
    imgbg: img1album2,
    imgbg2: img2album2,
    imgbg3: img3album2,
    imgbg4: img4album2,
    name: 'album2',
  },
  {
    id: 3,
    imgbg: img1album3,
    imgbg2: img2album3,
    imgbg3: img3album3,
    imgbg4: img4album3,
    name: 'album3',
  },
  {
    id: 4,
    imgbg: img1album4,
    imgbg2: img2album4,
    imgbg3: img3album4,
    imgbg4: img4album4,
    name: 'album4',
  },
  {
    id: 5,
    imgbg: img1album5,
    imgbg2: img2album5,
    imgbg3: img3album5,
    imgbg4: img4album5,
    name: 'album5',
  },
  {
    id: 6,
    imgbg: img1album3,
    imgbg2: img2album3,
    imgbg3: img3album3,
    imgbg4: img4album3,
    name: 'album3',
  },
];

export const AlbumLoadAll = [
  {
    id: 7,
    imgbg: img1album1,
    imgbg2: img2album1,
    imgbg3: img3album1,
    imgbg4: img4album1,
    name: 'album1',
  },
  {
    id: 8,
    imgbg: img1album2,
    imgbg2: img2album2,
    imgbg3: img3album2,
    imgbg4: img4album2,
    name: 'album2',
  },
  {
    id: 9,
    imgbg: img1album3,
    imgbg2: img2album3,
    imgbg3: img3album3,
    imgbg4: img4album3,
    name: 'album3',
  },
  {
    id: 10,
    imgbg: img1album4,
    imgbg2: img2album4,
    imgbg3: img3album4,
    imgbg4: img4album4,
    name: 'album4',
  },
  {
    id: 11,
    imgbg: img1album5,
    imgbg2: img2album5,
    imgbg3: img3album5,
    imgbg4: img4album5,
    name: 'album5',
  },
  {
    id: 12,
    imgbg: img1album3,
    imgbg2: img2album3,
    imgbg3: img3album3,
    imgbg4: img4album3,
    name: 'album3',
  },
  {
    id: 9,
    imgbg: img1album3,
    imgbg2: img2album3,
    imgbg3: img3album3,
    imgbg4: img4album3,
    name: 'album3',
  },
  {
    id: 7,
    imgbg: img1album1,
    imgbg2: img2album1,
    imgbg3: img3album1,
    imgbg4: img4album1,
    name: 'album1',
  },
  {
    id: 11,
    imgbg: img1album5,
    imgbg2: img2album5,
    imgbg3: img3album5,
    imgbg4: img4album5,
    name: 'album5',
  },
  {
    id: 8,
    imgbg: img1album2,
    imgbg2: img2album2,
    imgbg3: img3album2,
    imgbg4: img4album2,
    name: 'album2',
  },
  {
    id: 12,
    imgbg: img1album3,
    imgbg2: img2album3,
    imgbg3: img3album3,
    imgbg4: img4album3,
    name: 'album3',
  },
  {
    id: 10,
    imgbg: img1album4,
    imgbg2: img2album4,
    imgbg3: img3album4,
    imgbg4: img4album4,
    name: 'album4',
  },
  {
    id: 8,
    imgbg: img1album2,
    imgbg2: img2album2,
    imgbg3: img3album2,
    imgbg4: img4album2,
    name: 'album2',
  },
  {
    id: 9,
    imgbg: img1album3,
    imgbg2: img2album3,
    imgbg3: img3album3,
    imgbg4: img4album3,
    name: 'album3',
  },
  {
    id: 10,
    imgbg: img1album4,
    imgbg2: img2album4,
    imgbg3: img3album4,
    imgbg4: img4album4,
    name: 'album4',
  },
  {
    id: 11,
    imgbg: img1album5,
    imgbg2: img2album5,
    imgbg3: img3album5,
    imgbg4: img4album5,
    name: 'album5',
  },
];
